#!/bin/sh
#PBS -l walltime=60:00:00
#PBS -A COMP
#PBS -N readSequenceMatcher
#PBS -l nodes=4:ppn=4,mem=32g
#PBS -d /home/nmharjan/readSequenceMatcher
#PBS -j oe
#PBS -o /home/nmharjan/readSequenceMatcher/log.log
#PBS -e /home/nmharjan/readSequenceMatcher/run-job-std-error.log
#PBS -m abe
#PBS -M nmharjan@memphis.edu

cd /home/nmharjan/readSequenceMatcher

#
module load python/3.4.3
python3 pairEndReadSearch.py false true true fmIndex/fmIndex_dataset_withError_sm.pkl data/dataset_withError/sm_withError/reference data/dataset_withError/sm_withError/data1 data/dataset_withError/sm_withError/data1

